name: CI

on:
  push:
    branches: [ main, 'feature/**' ]
  pull_request:
    branches: [ main ]

jobs:
  # Job 1: Unit Tests (includes build and code quality checks)
  unit-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: ['22']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run unit tests
      run: npm test
      env:
        NODE_ENV: test
        
    - name: Run schema compatibility tests
      run: npm test -- src/tests/unit/schemas/schema-compatibility.test.ts
      env:
        NODE_ENV: test

  # Job 2: Integration Tests (Skipped in CI - requires OAuth tokens)
  # integration-tests:
  #   runs-on: ubuntu-latest
  #   needs: unit-tests
  #   if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
  #   
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #     
  #   - name: Setup Node.js
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: '22'
  #       cache: 'npm'
  #       
  #   - name: Install dependencies
  #     run: npm ci
  #     
  #   - name: Run integration tests (subset)
  #     run: |
  #       # Integration tests require OAuth tokens - run locally only
  #       echo "Integration tests skipped in CI (require OAuth tokens)"
  #       echo "To run locally: npm run dev test:integration:direct"
  #     env:
  #       NODE_ENV: test

  # Job 3: Coverage Report
  coverage:
    runs-on: ubuntu-latest
    needs: unit-tests
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests with coverage
      run: npm run test:coverage
      env:
        NODE_ENV: test
        
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/
        retention-days: 30